# This workflow will be able to manage:
# - creation of a release branch
# - create a PR to main and develop

name: Gitflow - Create Release

on:
  workflow_dispatch:

jobs:
  display-message-inherit:
    runs-on: ubuntu-latest
    steps:
      - uses: grasdouble/github-action/.github/workflows/demo-inerit-secret.yml@test-inherit-secrets
