# This workflow will call a reusable workflow
# the goal is to demonstrate a usage of the option inherit

name: Demo - Inherit Secrets

on:
  workflow_dispatch:

jobs:
  display-message-inherit:
    uses: grasdouble/github-action/.github/workflows/demo-inherit-secret.yml@test-inherit-secrets
    secrets: inherit
